# Generated by Django 3.2 on 2021-05-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('tilte', models.CharField(max_length=50)),
                ('head0', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
