# Generated by Django 3.2 on 2021-05-09 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='head0',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='genre',
            field=models.CharField(default='no genre', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 4, 42, 13, 155635, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tilte',
            field=models.CharField(default='no title', max_length=50),
        ),
    ]
