# Generated by Django 3.2 on 2021-05-10 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainblogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintitle1', models.CharField(default='no title', max_length=50)),
                ('maintitle2', models.CharField(default='no title', max_length=50)),
                ('maintitle3', models.CharField(default='no title', max_length=50)),
                ('paragraph1', models.CharField(default='', max_length=5000)),
                ('paragraph2', models.CharField(default='', max_length=5000)),
                ('paragraph3', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField(default=datetime.datetime(2021, 5, 10, 11, 7, 7, 503785, tzinfo=utc))),
                ('made_by', models.CharField(default='Blogtech Admin', max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 10, 11, 7, 7, 503785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
