# Generated by Django 3.2 on 2021-05-10 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210510_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainblogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateField(default=datetime.datetime(2021, 5, 10, 12, 0, 45, 8961, tzinfo=utc))),
                ('maintitle1', models.CharField(default='no title', max_length=50)),
                ('maintitle2', models.CharField(default='no title', max_length=50)),
                ('maintitle3', models.CharField(default='no title', max_length=50)),
                ('paragraph1', models.CharField(default='', max_length=5000)),
                ('paragraph2', models.CharField(default='', max_length=5000)),
                ('paragraph3', models.CharField(default='', max_length=5000)),
                ('made_by', models.CharField(default='Blogtech Admin', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='made_by',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='maintitle1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='maintitle2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='maintitle3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph3',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 10, 12, 0, 45, 8961, tzinfo=utc)),
        ),
    ]
