# Generated by Django 3.2 on 2021-05-10 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210510_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='newpost_id',
            field=models.IntegerField(default=6, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 10, 14, 38, 50, 113465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mainblogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 10, 14, 38, 50, 113465, tzinfo=utc)),
        ),
    ]
