# Generated by Django 3.2 on 2021-05-11 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210511_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainblogpost',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 11, 16, 1, 26, 241293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mainblogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 11, 16, 1, 26, 241293, tzinfo=utc)),
        ),
    ]
