# Generated by Django 3.2 on 2021-05-11 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210511_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainblogpost',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 11, 16, 2, 32, 40419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mainblogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 11, 16, 2, 32, 41449, tzinfo=utc)),
        ),
    ]
