# Generated by Django 3.2 on 2021-05-13 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210513_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='about',
            field=models.CharField(default='Hey Readers Welcome to Blogtech. for more such Awesome blogs click on next blog. If you love the blog Please like , Comment and Share.', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 5, 45, 43, 828084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mainblogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 5, 45, 43, 838821, tzinfo=utc)),
        ),
    ]
