# Generated by Django 3.2 on 2021-05-13 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210513_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainblogpost',
            name='thumbnail2',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='mainblogpost',
            name='thumbnail3',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 7, 21, 32, 539451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mainblogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 7, 21, 32, 539451, tzinfo=utc)),
        ),
    ]
